# Project policies.
#
# These policies can be enforced using `cargo deny check`.

[advisories]
ignore = []

[licenses]
# Allow common OSI-approved, non-copyleft licenses.
allow = [
    "0BSD",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "MIT",
    "Unicode-3.0",
]

[licenses.private]
# This crate is unpublished/unreleased, so ignore license requirements for it.
ignore = true

[bans]
deny = [
    # OpenSSL has caused endless deployment and build problems. We use rustls
    # for TLS everywhere.
    { name = "openssl" },
    { name = "openssl-sys" },
]

# Ignore duplicate versions of these crates (pulled in by different dependencies).
skip = []
