#!/usr/bin/env python3
##
## Unpack a table-of-contents file
##
import os, sys, re

if len(sys.argv) < 2:
    fp = sys.stdin
    if sys.stdin.isatty():
        print("[reading from standard input]", file=sys.stderr)
else:
    fp = open(sys.argv[1], 'rb')

chk = fp.read(3)
if chk != b'XM2':
    print("Input is not in the correct format.", file=sys.stderr)
    sys.exit(1)

data = {}
num_read = 0
while True:
    flen = ord(fp.read(1))
    num_read += 1
    if flen == 255:
        break

    fname = fp.read(flen)
    num_read += len(fname)
    print("File name (length %d): %s" % (flen, fname), file=sys.stderr)

    keys = []
    nkeys = ord(fp.read(1))
    num_read += 1
    for pos in range(nkeys):
        klen = ord(fp.read(1))
        num_read += 1
        keys.append(fp.read(klen))
        num_read += klen

    data[fname] = keys
    if fp.read(1) != b'\xff':
        print("Warning:  Missing record terminator at position %d." % num_read,
              file=sys.stderr)
        num_read += 1

for k in sorted(data.keys()):
    print("%s:%s" % (k.decode('utf-8'), b','.join(data[k]).decode('utf-8')))

fp.close()

# Here there be dragons
