[package]
name = "xcalr"
version = "0.1.0"
edition = "2021"
license = "ISC OR MIT OR Apache-2.0"

[[bin]]
name = "xcalr"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
bytes = "1"
fluent-bundle = "0.15"
intl-memoizer = "0.5"
tokio = { version = "1", features = ["net"] }
unic-langid = "0.9"
