[package]
name = "xcalr"
version = "0.1.0"
edition = "2021"
license = "ISC OR MIT OR Apache-2.0"

[[bin]]
name = "xcalr"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
async-trait = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
dcts = { path = "../../crates/dcts" }
fluent-bundle = "0.15"
intl-memoizer = "0.5"
miette = { workspace = true }
tokio = { workspace = true, features = ["macros", "net", "rt-multi-thread", "sync"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
unic-langid = "0.9"
uuid = { workspace = true }

[dev-dependencies]
dcts = { path = "../../crates/dcts", features = ["test-support"] }
xcal_test_tools = { path = "../../crates/xcal_test_tools" }
